# Generated by Django 5.0.6 on 2024-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='AssignaturesImpartides',
        ),
    ]
